spring.application.name=ledger-service
server.port=9002
spring.datasource.url=jdbc:mysql://localhost:3306/ledger_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Shwetan@21

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ledger.platform.account-id=LACC_550e8400e29b41d4a716446655440000
ledger.gst.account-id=LACC_7f3a91c84e2b4d6a91c2f840e29b41d4